Add a new option --persist-key
bitwarden/cli pull request #179
Opened 2020-11-09 18:41 UTC by estheruary

A new global option (and env variable) to save the session key to local storage. You only have to persist the key once (on any login event) and subsequent runs will neither require a key nor the `BW_SESSION` environment variable to be set.

2020-11-09 18:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/cli?pullRequest=179) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/cli?pullRequest=179) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/cli?pullRequest=179) it.</sub>

2020-11-09 21:13 UTC, cscharf requested changes
Hi @estheruary , thanks for the submission! I've included some feedback and am open for discussion, great work! I do also see the Logout command missing from the PR for consideration in destroying the persisted key on logout.

cc: @kspearrin

2020-11-09 21:13 UTC, cscharf commented on src/commands/unlock.command.ts
> +                await this.storageService.save('sessionKey', process.env.BW_SESSION);
Reference constance service here as well.

2020-11-09 21:13 UTC, cscharf commented on src/commands/unlock.command.ts
> +import { LowdbStorageService } from 'jslib/services/lowdbStorage.service';
see Login command for reference regarding use of abstraction here and constructor injection accordingly.

2020-11-09 21:13 UTC, cscharf commented on src/program.ts
> +            process.env.BW_PERSIST_KEY = 'true';
Theoretically this as this could potentially open up unintended side-effects or session hijacking if another machine administrator added a global environment variable to persist the key and was able to them detect change on and hijack local storage to pull in the session key via script, daemon, background service, etc.

I only bring this up due to the nature of the CLI being available on different platforms we can't be certain it will always be a Linux environment with proper controls in place against this things.

My suggestion would be the maintain the current running instance flag for this command and have that argument passed into each command that would persist it (to my knowledge would only be the login/unlock commands); where all other commands simply read/detect/or destroy the value persisted, if persisted already.

2020-11-10 03:56 UTC, cmbconcretefire commented on src/program.ts
> +            process.env.BW_PERSIST_KEY = 'true';
There's a bunch of code jibberish here that I could understand if I wanted to. No desire. 

Bottom line > Somewhere in the option section (if there isn't one, make one), give the USER the option to keep it on or off........... I assure you, 99% of the people smart enough to use Bitwarden already know keeping it open or unlocked for an entire session is shady....... we know....... ERgo: Give us credit to either exit out of bitwarden altogether to do other business where turning it OFF would be safer....... I don't know. I just want a simple option to keep the vault open and even possibly pre-load the password...........  *I AM RESPONSIBLE* for the safety of my machine. ..... >> Warnings and explanations to the user , or laymen, is appropriate. Sure.......but turn on those options and give them to us please. Thank you.

2020-11-10 15:55 UTC, kspearrin commented
I am not sure this is in scope with something we want to support in the CLI. A user should already be able to persist the session key to storage by setting the BW_SESSION environment variable on the machine in a persistent way, right?

2020-11-10 18:32 UTC, estheruary commented on src/program.ts
> +            process.env.BW_PERSIST_KEY = 'true';
@cscharf That makes sense and is how I originally had it but then I realized that if the vault is locked then basically any action triggers an unlock which is why I made it global. I think taking away the environment variable is fine but it will make the code a little inconsistent since all the other flags have and set environment variables.

2020-11-10 19:28 UTC, cscharf commented on src/program.ts
> +            process.env.BW_PERSIST_KEY = 'true';
hmm, will think about that. @estheruary , Did you see Kyle's comments regarding support in general around persistent session key?

2020-11-10 19:53 UTC, estheruary commented
@kspearrin Yeah, and that's ultimately what I do but I got @'d on an issue about having an option to persist the key without setting an environment variable. Setting the key in this manner I think has some benefits.

* It's clunky to set session-global env variables on Linux so people store the variables in their `*rc` files which makes it shell dependent. And scripts, hotkeys, whatever that don't run from their shell won't pick up the variable. There's lots of ways you could make it work but its more effort than just having `bw` do it for you and be done with it.
* Bitwarden CLI already has it's own storage service. Why split it up?
* Removing and rotating the key isn't something that we can do right now. We can invalidate the key with a lock/logout but it still sticks around in their config.

2020-11-11 21:27 UTC, cmbconcretefire commented on src/program.ts
> +            process.env.BW_PERSIST_KEY = 'true';
I don't know if you guys are even seeing me, ignoring me, etc....... ??

Can I turn the vault to always on? Yes or no? If yes, how? Exactly. Thank you.

2020-11-12 14:31 UTC, cscharf commented on src/program.ts
> +            process.env.BW_PERSIST_KEY = 'true';
@cmbconcretefire, I think it would be beneficial for you to open a thread on our [community user-to-user support forum](https://community.bitwarden.com/c/support/6) to get a broader answer and/or some creative feedback on how to accomplish that (it's not use-case I'm familiar with). Some of our customer success folks and others monitor those forums as well and may be able to help out with what you're asking. Here in a PR it'll get a little buried as it's not necessarily pertinent to the discussion around the code changes being submitted themselves.

2020-11-14 03:13 UTC, cmbconcretefire commented on src/program.ts
> +            process.env.BW_PERSIST_KEY = 'true';
@cscharf I give up.

2022-05-02 16:08 UTC, emilBeBri commented
Yes, great work estheruary! When is this coming to a terminal near me?

2022-05-25 14:19 UTC, Hinton commented
Hi,

We are currently in the process of archiving this repository and moving the code and future development to the https://github.com/bitwarden/clients repository. This PR will be closed but feel free to re-open it again on https://github.com/bitwarden/clients.

2022-05-25 14:19 UTC, closed without merging