Response option outputs only json on stdout
bitwarden/cli pull request #197
Opened 2020-11-30 23:13 UTC by MGibson1

This PR is associated with issue #188 and bitwarden/jslib#214

# Objective

Specify use of cli console log service for console jslib-handled console logging

# Files Changed
* **package.json**: added debug scripts used like this: `npm run debug -- {{arguments here}}`
* **bw.ts**: included logService optional parameter on service constructors
* **nodeEnvSecureStorage.service.ts**: this is the stdout called out in #188, using the cliLogService automatically redirects to stderr if --response is set.

# Draft reason
**This PR needs to merge after bitwarden/jslib#214 and update jslib's submodule reference**

2020-12-04 21:13 UTC, cscharf requested changes

2020-12-04 21:13 UTC, cscharf commented on src/services/nodeEnvSecureStorage.service.ts
> +import { LogService } from 'jslib/abstractions';
Use the most specific path for `LogService`, should be `jslib/abstractions/log.service.ts`;

2020-12-07 17:21 UTC, cscharf approved these changes

2020-12-09 21:13 UTC, cscharf commented on package.json
> +        "@bitwarden/jslib": "file:jslib",
Will need to reverse these changes

2020-12-09 21:13 UTC, cscharf commented on tsconfig.json
> +    "module": "commonjs",
??

2020-12-09 21:27 UTC, MGibson1 commented on tsconfig.json
> +    "module": "commonjs",
I cannot get the package to build with `module: es6`. This is toying with an area of typescript that I struggle with, but I believe this is due to the export method used by the [browser-process-hrtime](https://github.com/kumavis/browser-process-hrtime/blob/master/index.js) package.

You either need to enable default imports (or use emcainterop), which breaks other packages, or a different module flag in `tsconfig`. This was the only option that seemed to work.

I'm worried about this change too. It would be required in every client no already using `commonjs` and I don't fully understand the repercussions of that.

2020-12-14 17:12 UTC, cscharf approved these changes

2020-12-14 17:29 UTC, merged