Migrate appveyor to actions
bitwarden/cli pull request #207
Opened 2020-12-28 16:31 UTC by joseph-flinn

## Change Summary
Switching over to Github Actions from AppVeyor

## Files Changed
- .github/workflows/build.yml

## Notes
All but `release` based tasks have been tested

2020-12-28 16:45 UTC, kspearrin commented on .github/workflows/build.yml
> +        run: cloc --include-lang TypeScript,JavaScript,HTML,Sass,CSS --vcs git
I don't think these are the proper params for CLI. According to AppVeyor build, we are using:

```
cloc --include-lang TypeScript,JavaScript --vcs git
```

2020-12-28 16:45 UTC, kspearrin commented
On a quick review, looks like we are missing some steps still, around ResourceHacker?

2021-01-11 18:32 UTC, joseph-flinn commented
> On a quick review, looks like we are missing some steps still, around ResourceHacker?


Phew, that was a lot of commits. Too bad there isn't a way to do all of the workflow testing locally... I believe that I've covered all of the tasks, but may still be missing something. AppVeyor is difficult to follow with all of the environment dependancies.

2021-01-11 18:33 UTC, joseph-flinn commented on .github/workflows/build.yml
> +        run: cloc --include-lang TypeScript,JavaScript,HTML,Sass,CSS --vcs git
Fixed

2021-01-11 21:10 UTC, joseph-flinn commented
I forgot one concern that I have. I'm not sure what the `WIN_PKG: C:\Users\appveyor\.pkg-cache\v2.5\fetched-v10.4.1-win-x64` portion of the code is other than a flag for ResourceHacker to run.

2021-01-13 18:36 UTC, cscharf commented
> I forgot one concern that I have. I'm not sure what the `WIN_PKG: C:\Users\appveyor\.pkg-cache\v2.5\fetched-v10.4.1-win-x64` portion of the code is other than a flag for ResourceHacker to run.

@kspearrin , any thoughts on this?

2021-01-13 18:54 UTC, joseph-flinn commented
> > I forgot one concern that I have. I'm not sure what the `WIN_PKG: C:\Users\appveyor\.pkg-cache\v2.5\fetched-v10.4.1-win-x64` portion of the code is other than a flag for ResourceHacker to run.
> 
> @kspearrin , any thoughts on this?

Actually, I figured it out while working on the the Directory-Connectory.

2021-01-14 21:02 UTC, kspearrin requested changes
Seem to be missing steps to attaching artifact binaries to releases.

2021-01-14 21:02 UTC, kspearrin commented on .github/workflows/build.yml
> +          cd ./dist
some scripts using forward slash some using back. Just be consistent.

2021-01-21 15:00 UTC, kspearrin reviewed
looks like you left some stuff from testing still in here.

also, I am still confused about our approach to the pkg cache. do we have to DL it every time? Can we cache some things between runs with github actions? maybe that is a follow up enhancement.

2021-01-21 15:00 UTC, kspearrin commented on .github/workflows/build.yml
> +          #echo "D:/a/cli/cli/scripts/resource_hacker" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
remove this stuff now?

2021-01-21 15:00 UTC, kspearrin commented on .github/workflows/build.yml
> +    if: false
?

2021-01-27 19:14 UTC, closed without merging