Add send to cli
bitwarden/cli pull request #222
Opened 2021-01-29 17:44 UTC by MGibson1

# Overview

Add Bitwarden Send capability to the Bitwarden CLI.

## Typical workflow

I imagine the most typical things to do with Send in the CLI will be to create them and receive them, so that workflow is streamlined.

> **Note**: `bw send` is a shortcut with some added default to `bw send create`, which is capable of more advanced operation.
>
>`bw receive` is a shortcut to `bw send receive`

#### Send

`bw send "some text"` is all that's needed to create a text send, while `bw send -f /path/to/file.ext` will create a file type send. By default, only the access URL is returned for easy sharing.

#### Receive

`bw receive **send'sURL**` is all that's needed to receive a send. By default, only the content of the send is returned. For text Send's, this means outputting the text to stdout. For File sends, the file is downloaded to the current working directory.

> **Note**: It is possible to test all string arguments as a path and require opt-out of sending valid paths, but I like the opt in for sending data from your filesystem to a server.

## Description of features

Two new commands are added: **send** and **receive**

### send

> Can also use `bw send create`, which allows creation using encoded json.

Usage: bw send [options] [command] <data>

Work with Bitwarden sends. A Send can be quickly created using this command or subcommands can be used to fine-tune the Send

**Arguments:**
  data                            The data to Send. Specify as a filepath with the --file option

**Options:**
  -f, --file                      Specifies that <data> is a filepath
  -d, --deleteInDays <days>       The number of days in the future to set deletion date, defaults to 7 (default: "7")
  --hidden                        Hide <data> in web by default. Valid only if --file is not set.
  -n, --name <name>               The name of the Send. Defaults to a guid for text Sends and the filename for files.
  --notes <notes>                 Notes to add to the Send.
  --fullObject                    Specifies that the full Send object should be returned rather than just the access url.
  -h, --help                      display help for command

**Commands:**
  list                            List all the Sends owned by you
  template <object>               Get json templates for send objects
  get [options] <id>              Get Sends owned by you.
  receive [options] <url>         Access a Bitwarden Send from a url
  create [options] [encodedJson]  create a Send
  edit [options] [encodedJson]    edit a Send

### receive

> Can also use `bw send receive`

Usage: bw receive [options] <url>

Access a Bitwarden Send from a url

Options:
  --password <password>          Password needed to access the Send.
  --passwordenv <passwordenv>    Environment variable storing the Send's password
  --passwordfile <passwordfile>  Path to a file containing the Sends password as its first line
  --obj                          Return the Send's json object rather than the Send's content
  --output                       Specify a file path to save a File-type Send to
  -h, --help                     display help for command

If a password is required, the provided password is used or the user is prompted.

## New Code Organization

The old program file housed all code commands. Commands deeper than one level down are handled as options. This is no longer necessary with the upgrade to commander 7.0.0.

I've moved command definition to different files based on what the command does:
* **program.ts**: cross-concern functions: login, logout, sync, config, etc
* **vault.program.ts**: commands dealing with vault items. These are still base level commands for backwards compatibility
* **send.program.ts**: commands dealing with Sends. Most of these commands are subcommands of `bw send`.

Commands classes belong to send are located in `src/commands/send` and are named, for example, `get.command.ts` as with vault. The class name for `get` would be `SendGetCommand`. **I did not extend this convention to vault commands.**

# Files Changed
* **packages.json/package-lock.json**: upgrade commander to 7.0.0 to enable deep commands
* **bw.ts**: split program commands by operational area
* **completion.command.ts**: command no longer has a parent, but program itself lists all commands. I diff'ed this output with previous and got the same result.
* **config.command.ts/config.command.ts/config.command.ts/create.command.ts/delete.command.ts/edit.command.ts/encode.command.ts/export.command.ts/generate.command.ts/get.command.ts/import.command.ts/list.command.ts/login.command.ts/status.command.ts/sync.command.ts**: commander 7.0.0 upgrade
* **download.command.ts**: abstraction to allow downloading of attachments and Send files with the same code
* **get.command.ts**: Mostly the vault changes are due to commander upgrade, but I also added Send templates here in order for them to be more discoverable and highly-linked
* **send/create.command.ts**: holds send's create send command. Both `bw send` and `bw send create` pipe through here.
* **send/edit.command.ts**: holds send's edit command. Works similarly to `bw edit`.
* **send/get.command.ts**: holds send's get command. Works similarly to `bw get`, but does not require a template since it only works on Send.
* **send/list.command.ts**: holds send's list command. Works similarly to `bw list`, but does not require a template since it only works on Sends.
* **send/receive.command.ts**: holds send's receive command, which accesses sends. One quirk is it will infinitely recurse asking for a send's password. Since we repeat password hashing each time, I don't see this as an issue and improves user experience to throwing you out of the interface on a typo.
* **sendAccessResponse.ts/sendFileResponse.ts/sendTextResponse.ts/sendResponse.ts**: CLI response models
* **program.ts/send.program.ts/vault.program.ts**: see *New Code Organization* above
* **utils.ts**: Helper to conver Node Buffers back to ArrayBuffers.

# Testing Concerns

Literally every command was touched due to the commander update.
* all commands and all options need to be verified
  * special attention should be paid to Send commands

There are a lot of new commands and uniformity of commands and return values should be evaluated

Ease of use should also be evaluated. My working theory is that `bw send` and `bw receive` will be most used and most people will just want the Send information directly from the receive command with no frills.

Testing on both selfhosted and cloud deployment (most testing during development was done locally, which is a cloud install)

Thorough testing of malformed Send urls. Error handling is in place, but this is a tricky area to cover well.

2021-01-29 19:58 UTC, kspearrin requested changes

2021-01-29 19:58 UTC, kspearrin commented on src/commands/completion.command.ts
> +
remove

2021-01-29 19:58 UTC, kspearrin commented on src/commands/generate.command.ts
> +    async run(cmdOptions: program.OptionValues): Promise<Response> {
seems the standard you've been using is to just use `options` for the name?

2021-01-29 19:58 UTC, kspearrin commented on src/commands/download.command.ts
> +    }
would this just be better as a static helper?

2021-01-29 19:58 UTC, kspearrin commented on src/commands/send/create.command.ts
> +        const hidden = req.text?.hidden ?? options.hidden; // defaults true
does that match web behavior defaults?

2021-01-29 19:58 UTC, kspearrin commented on src/commands/send/delete.command.ts
> +            this.sendService.delete(id);
does this delete with server?

2021-01-29 19:58 UTC, kspearrin commented on src/commands/send/edit.command.ts
> +export class SendEditCommand {
how are you handling adding/editing/removing password from an existing send?

2021-01-29 19:58 UTC, kspearrin commented on src/commands/send/get.command.ts
> +            filter = s => {
I think this breaks our existing style guide of using parens with all function parameters. So far example, this would be `(s) =>`

2021-01-29 19:58 UTC, kspearrin commented on src/commands/send/receive.command.ts
> +export class SendReceiveCommand extends DownloadCommand {
we call this "access" on the web, but I find of like "receive" too. We should be consistent though.

2021-01-29 19:58 UTC, kspearrin commented on src/utils.ts
> +    }
I think we have some NodeUtils in jslib that already have this kind of stuff

2021-01-29 20:01 UTC, MGibson1 commented on src/commands/download.command.ts
> +    }
I'd be OK with that, but I chose this method because I think its cleaner as long as we don't have multiple inheritance requirements.

I'd say it depends on whether this patter will repeat to the point of wishing we could extend multiple classes, that's an obvious no-no

2021-01-29 20:04 UTC, MGibson1 commented on src/commands/send/delete.command.ts
> +            this.sendService.delete(id);
woah good catch, no it's just local cache.

2021-01-29 20:05 UTC, MGibson1 commented on src/commands/generate.command.ts
> +    async run(cmdOptions: program.OptionValues): Promise<Response> {
yes, I changed the name to avoid shadowing options on line 12.

`options` seemed a better variable name for the final options and `cmdOptions` for the options as they come from the program.

2021-01-29 20:14 UTC, MGibson1 commented on src/commands/send/receive.command.ts
> +export class SendReceiveCommand extends DownloadCommand {
Yeah I struggled with this.

The reason I went this direction because I like the workflow.

I `bw send` a file and you `bw receive` the file. Access doesn't have that same flow. I think of that referring more to a storage than something sent.

I was thinking the act could be called receive while the items like `accessId` and `accessUrl` are still called access

2021-01-29 20:22 UTC, MGibson1 commented on src/utils.ts
> +    }
Moved to jslib

2021-02-01 17:08 UTC, kspearrin commented on src/commands/download.command.ts
> +    }
I am fine with either. It just seemed like the sharing here is being limited to a single function (no state properties or anything), so usually I do something like that as a simple helper. If you like it this way better, that's ok with me.

2021-02-01 17:08 UTC, kspearrin commented on src/commands/send/receive.command.ts
> +export class SendReceiveCommand extends DownloadCommand {
Sounds good to me. Stay with receive.

2021-02-01 17:41 UTC, MGibson1 commented on src/commands/send/create.command.ts
> +        const hidden = req.text?.hidden ?? options.hidden; // defaults true
No, I'll change to false

2021-02-01 18:01 UTC, MGibson1 commented on src/commands/send/edit.command.ts
> +export class SendEditCommand {
The intended workflow for that would be to first get the Send, edit it through jq or similar, pipe into encode, and finally pipe into a `send edit` command. For example:

```
node bw.js send get 4b0af114-a69d-4393-9346-acbe01794f0a | jq '.password="new password for this send"' | node bw.js encode | node bw.js send edit
```

2021-02-01 18:05 UTC, MGibson1 commented on src/commands/send/edit.command.ts
> +export class SendEditCommand {
removing is a good point, that doesn't work. :(

I can either add some logic to the edit command or add another command to set/remove password.

I think I'm partial to the edit command, you?

2021-02-01 18:07 UTC, MGibson1 commented on src/commands/send/get.command.ts
> +            filter = s => {
I thought we changed that style guide rule due to this PR: https://github.com/bitwarden/web/pull/772

2021-02-01 19:55 UTC, MGibson1 commented on src/commands/send/edit.command.ts
> +export class SendEditCommand {
I've implemented remove as a separate command, per our offline discussion.

2021-02-01 20:06 UTC, kspearrin submitted a review, later dismissed

2021-02-01 21:34 UTC, MGibson1 commented
@kspearrin, had to delete appveyor.yml to get through appveyor failing my builds, sorry

2021-02-02 16:14 UTC, cscharf commented on src/commands/send/get.command.ts
> +            filter = s => {
Yes we did... had we removed that everywhere it was present before? And this may have been my fault for approving that change (which I did) w/o understanding the format repercussions everywhere else.

2021-02-02 18:53 UTC, MGibson1 commented on src/commands/send/get.command.ts
> +            filter = s => {
per offline discussion, We'll keep this PR as it is and put in a concerted effort to move away from single-parameter parens.

Need to add this rule to tslint.config:
```
"arrow-parens": [true, "ban-single-arg-parens"]
```
per https://palantir.github.io/tslint/rules/arrow-parens/

2021-02-02 20:48 UTC, cscharf commented on src/commands/send/get.command.ts
> +            filter = s => {
See: https://app.asana.com/0/1199400159838939/1199883779619317/f (internally)

2021-02-02 21:14 UTC, cscharf requested changes
Sorry for leaving the same feedback, got 80% of the way through before I realized I could have just said it once or twice to apply everywhere.

2021-02-02 21:14 UTC, cscharf commented on src/models/response/sendResponse.ts
> +import { SendFileResponse } from './sendFileResponse';
Imports need to be in alphabetical ascending order by path name.

2021-02-02 21:14 UTC, cscharf commented on src/models/response/SendAccessResponse.ts
> +import { SendFileResponse } from './sendFileResponse';
May need to start a new group OR ensure the paths are in alphabetical order.

2021-02-02 21:14 UTC, cscharf commented on src/bw.ts
> +import { SendProgram } from './send.program';
Imports within a group need to be alphabetically ordered by path name.

2021-02-02 21:14 UTC, cscharf commented on src/commands/send/create.command.ts
> +import { SendService } from 'jslib/abstractions/send.service';
Imports within a group need to be alphabetically ordered by path name.

2021-02-02 21:14 UTC, cscharf commented on src/commands/send/edit.command.ts
> +import { SendResponse } from '../..//models/response/sendResponse';
Double `//` in the path name?

2021-02-02 21:14 UTC, cscharf commented on src/commands/send/receive.command.ts
> +import { CryptoService } from 'jslib/abstractions/crypto.service';
Imports within a group need to be alphabetically ordered by path name. I believe `.` comes before `F`, but not sure, linter should have complained.

2021-02-02 21:14 UTC, cscharf commented on src/commands/send/receive.command.ts
> +import { SendAccessRequest } from 'jslib/models/request/sendAccessRequest';
Imports within a group need to be alphabetically ordered by path name.

2021-02-02 21:14 UTC, cscharf commented on src/send.program.ts
> +import * as chk from 'chalk';
Imports within a group need to be alphabetically ordered by path name or module name in this case.

2021-02-02 21:14 UTC, cscharf commented on src/send.program.ts
> +import { SendResponse } from './models/response/sendResponse';
Same, I'll stop adding these comments now, just needs a general audit/2nd look.

2021-02-02 21:57 UTC, MGibson1 commented on src/commands/send/receive.command.ts
> +import { CryptoService } from 'jslib/abstractions/crypto.service';
I actually ran the linter on this (I know it doesn't seem like it)

Two things: first, apparently this tslint didn't have an ordering rule. Second, `npm run lint` doesn't show issues but `npx tslint src/**/*.ts` does. I don't know what's going on!

2021-02-02 23:34 UTC, cscharf commented on src/commands/send/receive.command.ts
> +import { CryptoService } from 'jslib/abstractions/crypto.service';
I know we have that rule in at least one of the other repos, and it should be documented on the wiki already. If you could add it that would be beautiful and likely help you get these corrected faster, thanks! I've also noticed the lack of output/feedback from just running `npm run lint` and have no idea why that is, but perhaps something to figure out at some point.

2021-02-03 15:46 UTC, MGibson1 commented on package.json
> +        "lint": "tslint 'src/**/*.ts' 'spec/**/*.ts' || true",
looks like globs are handled inside npm and encapsulating in `'` pushes this glob calculation to the shell, where it's handled properly.

I'm going to write PRs against the clients making this change

2021-02-03 17:19 UTC, cscharf approved these changes

2021-02-03 17:19 UTC, cscharf commented on tslint.json
> +    "ordered-imports": true
👍🏻

2021-02-03 17:21 UTC, joseph-flinn commented
We'll probably want to hold off on merging this until we release the latest version of the CLI

2021-02-03 17:23 UTC, cscharf commented
> We'll probably want to hold off on merging this until we release the latest version of the CLI

We can discuss @joseph-flinn , perhaps we can create a branch or tag based on the last commit we want to include in the release and/or create that branch and cherry pick any last fixes we want to get in outside of this commit.

2021-02-03 17:43 UTC, cscharf commented
Release is cut, free to merge.

2021-02-03 17:44 UTC, merged