Update workflows to new model
bitwarden/cli pull request #379
Opened 2021-09-30 14:09 UTC by vgrassia

This PR is for updating our existing pipelines to the Build/Test/Release model.

2021-10-04 11:06 UTC, joseph-flinn requested changes

2021-10-04 11:06 UTC, joseph-flinn commented on .github/workflows/release.yml
> +        if: false
Looks like there is some testing code still in here.

2021-10-04 11:06 UTC, joseph-flinn commented on .github/workflows/release.yml
> +        if: false
Looks like there is some testing code still in here.

2021-10-04 11:06 UTC, joseph-flinn commented on .github/workflows/release.yml
> +        if: false
Looks like there is some testing code still in here.

2021-10-04 11:06 UTC, joseph-flinn commented on .github/workflows/release.yml
> +        run: npm run publish:npm
This is running an `npm run build:prod`. I wondering if we can build this in the previous workflow, zip it, and unzip it to the right directory here before running the `npm publish --access public`

2021-10-05 16:25 UTC, vgrassia commented on .github/workflows/release.yml
> +        if: false
Removed.

2021-10-05 16:25 UTC, vgrassia commented on .github/workflows/release.yml
> +        if: false
Removed.

2021-10-05 16:25 UTC, vgrassia commented on .github/workflows/release.yml
> +        if: false
Removed.

2021-10-05 17:59 UTC, vgrassia commented on .github/workflows/release.yml
> +        run: npm run publish:npm
I added an artifact that is the whole `build` folder which should be all that's needed for the `npm publish` command.  Let me know what you think.

2021-10-05 19:29 UTC, joseph-flinn approved these changes

2021-10-05 19:30 UTC, joseph-flinn commented on .github/workflows/release.yml
> +        run: npm run publish:npm
I like it!

2021-10-05 20:20 UTC, merged