Feature/password protected export
bitwarden/cli pull request #446
Opened 2022-01-14 22:55 UTC by MGibson1

## Type of change

- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective
Add password protected export/import to CLI. Companion PR bitwarden/jslib#612.

## Code changes
* **launch.json**: Adds variables I've found useful in debugging via vscode
* **bw.ts**: update dependencies
* **export.command**: Further abstracts the types of exports you can make, since password protection is just a wrapper around other exports.
* **import.command**: 
  * Grabs password for file
  * adds `bitwardenpasswordprotected` to know importers. This will need to be non-hard coded once we have this importer added to the featured import types list (once it's in web)
* **unlock.command**:  extracts password query to single location
* **en.messages**: adds import password failure message
* **utils**: adds common password methods for gathering a master password. This is also now that definition of priority of password retrieval methods.
* **vault.program**: add password protect option to export command, which encrypts any created export with a prompted password.

## Testing requirements
Functionality testing and integration tests are required. A significant amount of input validation is done through unit testing, but round tripping is needed.

## Before you submit

- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [x] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-02-08 01:15 UTC, eliykat requested changes
One minor change, otherwise the code looks good, my only feedback is about the UX.

1. We treat the password protection inconsistently; when you export it, the format is `csv` or `json` with an extra flag `--passwordprotect`. But when you import it, the format is now `bitwardenpasswordprotected`, with no flag. Logically the import format should be the same as the export format. I made this mistake by exporting a password protected csv and then trying to import it as a csv, and got an error (which is particularly confusing because I can see it's a csv file on my harddrive).

2. What's the use case for supporting json and csv export when the encrypted file itself is always a json? I exported an encrypted csv and found it was just a json with a `.csv` extension - which is not a real csv. I get that the encrypted data itself decrypts into that underlying format, but if it goes directly into the bw client, would the user ever notice?

3. The distinction between 'encrypted' and 'password protected' is confusing; do we have any plans to clarify this? Maybe one for product/design.

2022-02-08 01:15 UTC, eliykat commented on src/commands/import.command.ts
> +      .concat([{ id: "bitwardenPasswordProtected", name: "Bitwarden Password Protected" }])
`id` should be lowercase

2022-02-08 01:26 UTC, MGibson1 commented
Thanks for your insight, especially around formats.

I think 1 and 2 have roughly the same answer.  The thinking is that maybe you're exporting and want to import somewhere else and perhaps that somewhere else supports only one of our formats. We're planning on including an export file decryptor at some point to enable that kind of flow. This means that password protection is an option on top of an export.

In contrast I approached importers from the perspective that you have a file, what type of file is that? I can definitely see the confusion, though. I just hesitate to remove the above option and have the "correct" importer option be a different file type than the file actually is.

I think probably the best solution is to allow password protection on only unencrypted json exports.

As for three, I would absolutely love to just get rid of encrypted json entirely, but I am worried someone relies on it today and this export doesn't fill _exactly_ the same use-case. This was actually another reason I added password protection as an option rather than a format. I think it's less confusing if it's an option on top of everything else than two different encrypted formats

2022-02-08 03:40 UTC, MGibson1 commented on src/commands/import.command.ts
> +      .concat([{ id: "bitwardenPasswordProtected", name: "Bitwarden Password Protected" }])
I'm confused, it is. Can you suggest an edit to clarify?

2022-02-08 03:53 UTC, eliykat commented on src/commands/import.command.ts
> +      .concat([{ id: "bitwardenPasswordProtected", name: "Bitwarden Password Protected" }])
```suggestion
      .concat([{ id: "bitwardenpasswordprotected", name: "Bitwarden Password Protected" }])
```

2022-02-08 13:41 UTC, MGibson1 commented on src/commands/import.command.ts
> +      .concat([{ id: "bitwardenPasswordProtected", name: "Bitwarden Password Protected" }])
ah of course, thanks.

2022-02-19 15:55 UTC, MGibson1 commented
There have been some functional improvements both in jslib and here.

The concept of a password protected format is basically gone. There is not inner format, now. It's all json now. However, there is still a special importer that accepts a required password. Client are expected to catch a special error from the json importer and re-attempt after prompting for a password from the user.

I've also made some changes that resolve our weird export master password reprompt and unifies the concept of an encrypted export with encryption options of account- or password-encrypted.

2022-02-22 06:18 UTC, eliykat requested changes
I like the idea of account- vs. password-protected export, nice way to explain the difference. And if I understand correctly, this difference is hidden from the user when they import, which is great. I think this addresses all my UX concerns.

Tangentially related: I noticed that we don't check the export format in `ExportCommand`, it'll just default to json if the format is invalid. So if you write `encryptedJson` instead of `encrypted_json` then you'll accidentally export your entire vault in plaintext, which seems bad. Could you throw in a quick check for this while you're here? Or I can submit a separate ticket.

2022-02-22 06:18 UTC, eliykat commented on src/commands/import.command.ts
> +      .concat([{ id: "bitwardenPasswordProtected", name: "Bitwarden Password Protected" }])
bump if this is still required

2022-02-22 06:18 UTC, eliykat commented on src/commands/import.command.ts
> +  private async promptPassword() {
We do this in both import and export services (and maybe elsewhere?). Is it worth lifting up to `Utils`? Or putting a more general wrapper around simple one-line requests for information?

2022-02-22 17:07 UTC, MGibson1 commented on src/utils.ts
> +    if (password == null || password === "") {
not the same as `nullOrEmpty`, but I added that helper, too

2022-02-22 17:11 UTC, MGibson1 commented on src/utils.ts
> +        if (process.env[options.passwordEnv]) {
I don't see why. If we do, we'll need to do the same `nullOrEmpty` check that's done automatically with this truthiness test.

2022-02-22 17:20 UTC, MGibson1 commented on src/commands/export.command.ts
> -      (await this.keyConnectorService.getUsesKeyConnector())
yup, this PR does remove export MP/OTP requirement.

No one has spoken up in favor of the requirement in quite some time and it really doesn't do anything with the `list` command existing

2022-02-22 21:22 UTC, eliykat commented on src/commands/export.command.ts
> -      (await this.keyConnectorService.getUsesKeyConnector())
Sounds good, please just make sure to tell documentation if anything needs to be updated on their end

2022-02-22 21:32 UTC, eliykat commented on src/utils.ts
> +        if (process.env[options.passwordEnv]) {
From my comment in the jslib PR:
> I thought it was our code style, and is definitely my preference because it's clearer what you're testing (false? null/undefined? empty string? 0? etc). But if I'm mistaken here that's fine.

`nullOrEmpty` seems more expressive to me.

2022-02-23 20:08 UTC, MGibson1 commented on src/commands/export.command.ts
> +  private async promptPassword(password: string | boolean) {
It'll be undefined with unused flag, but otherwise correct.

This behavior is what's baked into commander. If we want this behavior we need to do this kind of logic somewhere. I'll add comments

2022-02-23 21:37 UTC, eliykat commented on src/utils.ts
> +        if (process.env[options.passwordEnv]) {
leaving this as discussed

2022-02-23 21:37 UTC, eliykat approved these changes

2022-02-23 21:37 UTC, MGibson1 commented on src/utils.ts
> +      if (process.env.BW_NOINTERACTION !== "true") {
Not a bad idea, but I think this is out of scope

2022-02-23 21:47 UTC, merged

2022-03-03 16:02 UTC, ashutoshsaboo commented
@MGibson1 @eliykat is there any documentation on how to use this feature with the CLI?

2022-03-03 21:36 UTC, eliykat commented
@ashutoshsaboo This feature will be in the v 1.22.0 release, scheduled for 16/17 March.

You use it by exporting to the `encrypted_json` format with a new `--password [password]` argument:

```
bw export --format encrypted_json --password mySecretPassword
```

The new argument is also noted in the `bw export --help` output.

@fschillingeriv can you please make sure the [CLI export](https://bitwarden.com/help/cli/#export) docs are updated to include this feature.

2022-03-04 10:14 UTC, ashutoshsaboo commented
Got it thanks @eliykat , will look forward to the update in docs you linked above as well. On another note - if I'm not wrong, wasn't the request in this github issue - https://github.com/bitwarden/cli/issues/232 - to add support for encrypted exports with personal api key token? If yes, why was that issue resolved via this PR - shouldn't it be still open? That PR was resolved and I got a notification, that's how I stumbled upon this. 

Please feel free to correct me if I'm missing anything?

2022-03-05 16:21 UTC, Alexander-Shukaev commented
Does this also take care of attachments?

2022-03-05 16:35 UTC, Alexander-Shukaev commented
> Got it thanks @eliykat @MGibson1 , will look forward to the update in docs you linked above as well. On another note - if I'm not wrong, wasn't the request in this github issue - #232 - to add support for encrypted exports with personal api key token rather than password? If yes, why was that issue resolved via this PR - shouldn't it be still open? That issue was resolved via this PR and I got a notification as I was subscribed to the linked issue, that's how I stumbled upon this PR.
> 
> Please feel free to correct me if I'm missing anything?

I second this question.  Could spend a few hours reading through the code, but if possible it'd be great to receive a straight answer.  API key to merely download the encrypted vault (including attachments) was the primary goal, so that the actual master password never even touches the environment where such download (and presumably a backup of it) is happening.

2022-03-06 02:59 UTC, MGibson1 commented
Oops, thank you @Alexander-Shukaev & @Alexander-Shukaev. I misread the issue when attaching the PR. I'm glad you two caught that!

2022-03-06 03:07 UTC, MGibson1 commented
@Alexander-Shukaev No, attachments are not exported with this. Attachment export is coming, just not yet.