Performance: Replace jsdom with xmldom, target es2020, lazy load inquirer and jszip
bitwarden/cli pull request #530
Opened 2022-05-12 03:38 UTC by blopker

## Type of change

- [x] Bug fix
- [ ] New feature development
- [x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

This PR is to improve the startup performance of the CLI a bit, which currently takes ~1 second to run `bw status` to run on my M1 Mac. After these changes, that same command takes around 600ms. Not a huge difference, but definitely noticeable. 

## Code changes

There are 2 main changes here. The first is to swap JSDOM for xmldom. The reason for this is that JSDOM has a pretty large import cost, where xmldom is almost instant. The second change is to lazy load the inquirer and jszip imports since they also both have large import costs. I don't know of good alternatives to them, but lazy loading their imports at least makes only the commands that use them pay the performance costs.

To make lazy loading work, the target JS target had to be changed to es2020. A nice side effect of that is that the final binary is now ~10mb smaller, which seems like it also helps with startup time.

## Testing requirements

I've tested, but commands that use jszip and inquirer could be good to get more.

## Before you submit

- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-05-12 03:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/cli?pullRequest=530) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/cli?pullRequest=530) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/cli?pullRequest=530) it.</sub>

2022-05-24 20:51 UTC, Hinton requested changes
Hi @blopker,

This seems like interesting changes and would love to get them included. I've done a quick PR review and found one major issue with xmldom. I suspect we could continue to use jsdom if we import it on need in the importers instead.

2022-05-24 20:51 UTC, Hinton commented on src/utils.ts
> +          JSZip.loadAsync(data).then(
This seems to not work, I think we need to use the `default` here.

```suggestion
          JSZip.default.loadAsync(data).then(
```

2022-05-24 20:51 UTC, Hinton commented on src/utils.ts
> +        const answer = await inquirer.createPromptModule({
We should extract this to a utils method which will make it easier to use it.

```ts
static async createPromptModule<T>(
	  questions: QuestionCollection<T>,
	  initialAnswers?: Partial<T>
): Promise<T> {
	const inquirer = await import("inquirer");
	  return inquirer.createPromptModule({
	  	output: process.stderr,
	  })(questions, initialAnswers);
}
```

2022-05-24 20:51 UTC, Hinton commented on src/bw.ts
> +(global as any).DOMParser = DOMParser;
XMLDom doesn't seem to support `document.querySelector` which is needed.

2022-05-24 20:52 UTC, Hinton commented
Also it seems `login.command.ts` in jslib still uses inquirer which drags it in for the whole project.

2022-05-24 21:00 UTC, blopker commented on src/bw.ts
> +(global as any).DOMParser = DOMParser;
Ah, good find. I didn't see where jsdom was being used so it was hard for me to test. I don't think using jsdom is a problem as long as it can be lazyloaded. Could you point out where it's used?

2022-05-24 21:01 UTC, blopker commented on src/utils.ts
> +        const answer = await inquirer.createPromptModule({
Smart. I'll put that in the next attempt.

2022-05-24 21:03 UTC, blopker commented
I did notice a few places in jslib where things could be optimized, but I didn't feel comfortable touching that since it seems to have many other projects depend on it?

2022-05-25 08:43 UTC, Hinton commented on src/bw.ts
> +(global as any).DOMParser = DOMParser;
Just the importer command I believe. We create a `DOMParser` which then immediately uses `document.querySelector`. If we lazy loaded the jsdom part before executing the import it "should" work I believe.

(For testing you can use the xml from https://github.com/bitwarden/jslib/blob/master/common/spec/importers/testData/safeInCloud/testData.xml.ts)

2022-05-25 14:19 UTC, Hinton commented
Hi,

We are currently in the process of archiving this repository and moving the code and future development to the https://github.com/bitwarden/clients repository. This PR will be closed but feel free to re-open it again on https://github.com/bitwarden/clients.

2022-05-25 14:19 UTC, closed without merging